### ISSUE TITLE
Most recent actions and scheduled events don't appear in my watchlist

### ISSUE THREAD

**Issue by jhoerr** [pingthepeople/ptp-web#65]
Action/scheduled event information isn't appearing on the watchlist. Repro with SB 4/5/15/16. All have actions (committee assignments). SB 4/16 have scheduled events (committee hearings).

**Comment by ohnoitsaustin** [comment]
fixed in https://github.com/pingthepeople/ptp-web/commit/77a8eca40b0df16c6797bf7eee2ea4ed1bc0c87f
