### ISSUE TITLE
Increase login session expiration time.

### ISSUE THREAD

**Issue by jhoerr** [pingthepeople/ptp-web#71]
I check PtP a few times a day and it seems like I have to reauthorize pretty often. Is there a way to lengthen the auth session time to a day or maybe a week?

**Comment by jhoerr** [comment]
[Is this the setting](https://github.com/pingthepeople/ptp-web/blob/master/config/session.php#L32) that needs to be chamged/bumped up?

**Comment by ohnoitsaustin** [comment]
Yup, that should do it

**Comment by jhoerr** [comment]
What's reasonable? 1 day? 1 week?

**Comment by jhoerr** [comment]
Fixed in 2.1.0
