### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by jhoerr** [pingthepeople/ptp-web#84]
I think the changes in #83 are a big improvement! I received the following error the first time I tried to log into the test site, but haven't been able to repro it. I don't know if it's related to any changes you made -- maybe just a transient bug?

![image](https://user-images.githubusercontent.com/1151206/36604323-6845d42c-188b-11e8-9ee5-8b03aaf0d49c.png)

**Comment by ohnoitsaustin** [comment]
Hmm, seems like a transient thing, I didn't change anything related to login. I'm wondering if the deploy broke your session or something. 

Either way, I'll get things updated so that we're not dumping debug info.

I'll try to dig in to logs and see if this is popping up on production.

**Comment by jhoerr** [comment]
Closing until we see again.
